general.import = [
  "~/.config/alacritty/dracula.toml",
]

[font]
size = 14
offset = { x = 0, y = 1 }
bold = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
normal = { family = "Hack Nerd Font Mono" }

# cmd-left as 'home'
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Command"

# cmd-right as 'end'
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Command"

[window]
decorations = "None"
padding = { x = 2, y = 2 }
option_as_alt = "OnlyLeft" # mac only: left 'option' as 'meta'
