[tools]
# lsps:
taplo = "latest"
lua-language-server = "latest"
"aqua:blopker/codebook" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@actions/languageserver" = "latest"
"npm:bash-language-server" = "latest"
"npm:quick-lint-js" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"

# linters/formatters:
shellcheck = "latest"
