[settings]
auto_install = false

[tools]
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

neovim = "nightly"
tree-sitter = "latest" # required for nvim-treesitter (compiling parsers)
usage = "latest" # requirement for some cli tools

bat = "latest"
cloudflared = "latest"
dive = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
jq = "latest"
pipx = "latest"
ripgrep = "latest"
yq = "latest"

"github:ankitpokhrel/jira-cli" = "latest"
"pipx:pgcli" = "latest"
"github:reviewdog/reviewdog" = "latest"
# "go:github.com/reviewdog/reviewdog/cmd/reviewdog" = "latest" # master branch
